spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eshare
    username: root
    password: 123456
  # redis 配置
  redis:
    # 地址
    host: 192.168.56.10
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池的最大数据库连接数
        max-active: 10
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
  data:
    redis:
      repositories:
        enabled: false
  # elasticsearch 配置

#  elasticsearch:
#    uris: http://localhost:9200

es:
  host: 192.168.56.11


server:
  port: 9001
#  servlet:
#    context-path: /api

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 开启sql日志
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

aliyun:
  access-key-id:
  access-key-secret:
  oss:
    endpoint:
    bucket:


token:
  # 令牌密钥明文
  secret: linjingshu
  # access-token配置
  access-token:
    # 令牌自定义标识
    header: access_token
    # 令牌有效期（默认30分钟）
    expireTime: 30
  #refresh-token
  refresh-token:
    header: refresh_token
    expireTime: 120

# 线程池配置参数
task:
  pool:
    corePoolSize: 10 # 设置核心线程数
    maxPoolSize: 20  # 设置最大线程数
    keepAliveSeconds: 300 # 设置空闲线程存活时间（秒）
    queueCapacity: 100 # 设置队列容量
    threadNamePrefix: "-signpolicy-asynnotify-" # 设置线程名称前缀
    awaitTerminationSeconds: 60 #  设置线程池等待终止时间(秒)

oauth:
  github:
    clientId:
    clientSecret:
    redirectURI: http://localhost:3000/githubCallback
    authorizeURL: https://github.com/login/oauth/authorize
    accessToken: https://github.com/login/oauth/access_token
    userInfo: https://api.github.com/user


logging.level.com.shu.eshare: debug
